'use client'

import { useEffect, useState } from 'react'
import { EDITORIAL_STATUSES, canTransitionEditorialStatus, type EditorialStatus } from '@/lib/editorial-workflow'

type Person={id:string;slug:string;name:string;editorialStatus:string}
type Timeline={id:string;objectId:string;objectTitle:string;title:string;dateFrom:string|null;editorialStatus:string}
type EventRow={id:string;slug:string;title:string;dateFrom:string|null;editorialStatus:string}
type MediaRow={id:string;objectTitle:string;altText:string;hasCurrentPair:boolean;editorialStatus:string}
type Relation={objectId:string;objectTitle:string;personId:string;personName:string;relationType:string}
type ObjectRow={id:string;title:string}
type SourceRow={id:string;title:string}
type WorkflowEntity='person'|'historical_event'|'timeline_entry'|'archive_media'

const STATUS_RU:Record<string,string>={draft:'черновик',review:'на проверке',changes_requested:'на доработке',approved:'одобрено',published:'опубликовано',archived:'в архиве'}
const ACTION_RU:Record<string,string>={draft:'В черновики',review:'На проверку',changes_requested:'Вернуть на доработку',approved:'Одобрить',published:'Опубликовать',archived:'В архив'}
const allowedTransitions=(status:string):EditorialStatus[]=>(EDITORIAL_STATUSES as readonly string[]).includes(status)?EDITORIAL_STATUSES.filter(s=>s!==status&&canTransitionEditorialStatus(status as EditorialStatus,s)):[]

export default function MemoryManager(){
  const[people,setPeople]=useState<Person[]>([]),[timeline,setTimeline]=useState<Timeline[]>([]),[events,setEvents]=useState<EventRow[]>([]),[media,setMedia]=useState<MediaRow[]>([]),[relations,setRelations]=useState<Relation[]>([]),[objects,setObjects]=useState<ObjectRow[]>([]),[sources,setSources]=useState<SourceRow[]>([])
  const[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
  const[name,setName]=useState(''),[slug,setSlug]=useState(''),[aliases,setAliases]=useState('')
  const[objectId,setObjectId]=useState(''),[timelineTitle,setTimelineTitle]=useState(''),[dateFrom,setDateFrom]=useState(''),[approximate,setApproximate]=useState(false)
  const[relationObjectId,setRelationObjectId]=useState(''),[personId,setPersonId]=useState(''),[relationType,setRelationType]=useState('')
  const[eventTitle,setEventTitle]=useState(''),[eventSlug,setEventSlug]=useState(''),[eventDate,setEventDate]=useState(''),[eventApproximate,setEventApproximate]=useState(false)
  const[linkTarget,setLinkTarget]=useState<'object'|'person'>('object'),[linkObjectId,setLinkObjectId]=useState(''),[linkPersonId,setLinkPersonId]=useState(''),[linkEventId,setLinkEventId]=useState(''),[linkRelationType,setLinkRelationType]=useState('')
  const[mediaObjectId,setMediaObjectId]=useState(''),[mediaTimelineId,setMediaTimelineId]=useState(''),[mediaFileUrl,setMediaFileUrl]=useState(''),[mediaCurrentUrl,setMediaCurrentUrl]=useState(''),[mediaSourceId,setMediaSourceId]=useState(''),[mediaRights,setMediaRights]=useState(''),[mediaAlt,setMediaAlt]=useState(''),[mediaDate,setMediaDate]=useState(''),[mediaApproximate,setMediaApproximate]=useState(false)
  async function load(){const[a,b,c]=await Promise.all([fetch('/api/admin/memory').then(r=>r.json()),fetch('/api/admin/objects').then(r=>r.json()),fetch('/api/admin/sources').then(r=>r.json())]);setPeople(Array.isArray(a.people)?a.people:[]);setTimeline(Array.isArray(a.timeline)?a.timeline:[]);setEvents(Array.isArray(a.events)?a.events:[]);setMedia(Array.isArray(a.media)?a.media:[]);setRelations(Array.isArray(a.relations)?a.relations:[]);setObjects(Array.isArray(b)?b:[]);setSources(Array.isArray(c)?c:[])}
  useEffect(()=>{void load()},[])
  async function submit(body:unknown,reset:()=>void){setError('');setNotice('');const r=await fetch('/api/admin/memory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){const b=await r.json().catch(()=>null)as{error?:string}|null;setError(b?.error??'Не удалось сохранить');return}reset();setNotice('Черновик сохранён');await load()}
  async function transition(entity:WorkflowEntity,id:string,status:string){setError('');setNotice('');setBusy(true);try{const r=await fetch('/api/admin/memory/workflow',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity,id,status})});if(!r.ok){const b=await r.json().catch(()=>null)as{error?:string}|null;setError(b?.error??'Не удалось изменить статус');return}setNotice('Статус обновлён');await load()}finally{setBusy(false)}}
  async function upload(file:File|undefined,apply:(url:string)=>void){if(!file)return;setError('');const fd=new FormData();fd.append('file',file);const r=await fetch('/api/admin/upload',{method:'POST',body:fd});if(!r.ok){const b=await r.json().catch(()=>null)as{error?:string}|null;setError(b?.error??'Не удалось загрузить изображение');return}const b=await r.json()as{original:string};apply(b.original)}
  const mediaTimeline=timeline.filter(t=>t.objectId===mediaObjectId)
  return <div className="space-y-6">
    {(error||notice)&&<p role="status" className={`rounded-lg p-3 text-sm ${error?'bg-red-50 text-red-700':'bg-emerald-50 text-emerald-700'}`}>{error||notice}</p>}
    <div className="grid gap-5 lg:grid-cols-3">
      <form onSubmit={e=>{e.preventDefault();void submit({kind:'person',person:{name,slug,aliases:aliases.split(',').map(x=>x.trim()).filter(Boolean)}},()=>{setName('');setSlug('');setAliases('')})}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Новый человек</h2><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Имя" className="w-full rounded-lg border p-2"/><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={slug} onChange={e=>setSlug(e.target.value)} placeholder="slug-latinicey" className="w-full rounded-lg border p-2"/><input value={aliases} onChange={e=>setAliases(e.target.value)} placeholder="Псевдонимы через запятую" className="w-full rounded-lg border p-2"/><button className="rounded-lg bg-slate-900 px-4 py-2 text-white">Создать черновик</button></form>
      <form onSubmit={e=>{e.preventDefault();void submit({kind:'timeline',entry:{objectId,entryType:'other',title:timelineTitle,dateFrom:dateFrom||null,approximate}},()=>{setTimelineTitle('');setDateFrom('');setApproximate(false)})}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Событие хронологии</h2><select required value={objectId} onChange={e=>setObjectId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите объект</option>{objects.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select><input required value={timelineTitle} onChange={e=>setTimelineTitle(e.target.value)} placeholder="Название события" className="w-full rounded-lg border p-2"/><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="w-full rounded-lg border p-2"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={approximate} onChange={e=>setApproximate(e.target.checked)}/>Приблизительная дата</label><button className="rounded-lg bg-slate-900 px-4 py-2 text-white">Создать черновик</button></form>
      <form onSubmit={e=>{e.preventDefault();void submit({kind:'objectPerson',objectId:relationObjectId,personId,relationType},()=>setRelationType(''))}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Связать человека с местом</h2><select required value={relationObjectId} onChange={e=>setRelationObjectId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите объект</option>{objects.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select><select required value={personId} onChange={e=>setPersonId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите человека</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required value={relationType} onChange={e=>setRelationType(e.target.value)} placeholder="Например: автор памятника" className="w-full rounded-lg border p-2"/><button className="rounded-lg bg-slate-900 px-4 py-2 text-white">Добавить связь</button></form>
      <form onSubmit={e=>{e.preventDefault();void submit({kind:'event',event:{slug:eventSlug,title:eventTitle,dateFrom:eventDate||null,approximate:eventApproximate}},()=>{setEventTitle('');setEventSlug('');setEventDate('');setEventApproximate(false)})}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Историческое событие</h2><input required value={eventTitle} onChange={e=>setEventTitle(e.target.value)} placeholder="Название события" className="w-full rounded-lg border p-2"/><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={eventSlug} onChange={e=>setEventSlug(e.target.value)} placeholder="slug-latinicey" className="w-full rounded-lg border p-2"/><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} className="w-full rounded-lg border p-2"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={eventApproximate} onChange={e=>setEventApproximate(e.target.checked)}/>Приблизительная дата</label><button className="rounded-lg bg-slate-900 px-4 py-2 text-white">Создать черновик</button></form>
      <form onSubmit={e=>{e.preventDefault();void submit(linkTarget==='object'?{kind:'objectEvent',objectId:linkObjectId,eventId:linkEventId,relationType:linkRelationType}:{kind:'personEvent',personId:linkPersonId,eventId:linkEventId,relationType:linkRelationType},()=>setLinkRelationType(''))}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Связать событие</h2><select value={linkTarget} onChange={e=>setLinkTarget(e.target.value as 'object'|'person')} className="w-full rounded-lg border p-2"><option value="object">С местом</option><option value="person">С человеком</option></select>{linkTarget==='object'?<select required value={linkObjectId} onChange={e=>setLinkObjectId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите объект</option>{objects.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select>:<select required value={linkPersonId} onChange={e=>setLinkPersonId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите человека</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<select required value={linkEventId} onChange={e=>setLinkEventId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Выберите событие</option>{events.map(ev=><option key={ev.id} value={ev.id}>{ev.title}</option>)}</select><input required value={linkRelationType} onChange={e=>setLinkRelationType(e.target.value)} placeholder="Например: посвящён событию" className="w-full rounded-lg border p-2"/><button className="rounded-lg bg-slate-900 px-4 py-2 text-white">Добавить связь</button></form>
      <form onSubmit={e=>{e.preventDefault();void submit({kind:'archiveMedia',media:{objectId:mediaObjectId,timelineEntryId:mediaTimelineId||null,captureFrom:mediaDate||null,approximate:mediaApproximate,fileUrl:mediaFileUrl,currentFileUrl:mediaCurrentUrl||null,sourceId:mediaSourceId,rightsStatus:mediaRights,altText:mediaAlt}},()=>{setMediaTimelineId('');setMediaFileUrl('');setMediaCurrentUrl('');setMediaRights('');setMediaAlt('');setMediaDate('');setMediaApproximate(false)})}} className="space-y-3 rounded-xl border bg-white p-4"><h2 className="font-semibold">Архивное фото «тогда/сейчас»</h2><select required value={mediaObjectId} onChange={e=>{setMediaObjectId(e.target.value);setMediaTimelineId('')}} className="w-full rounded-lg border p-2"><option value="">Выберите объект</option>{objects.map(o=><option key={o.id} value={o.id}>{o.title}</option>)}</select><select value={mediaTimelineId} onChange={e=>setMediaTimelineId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Без привязки к хронологии</option>{mediaTimeline.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><label className="block text-sm">Архивное фото{mediaFileUrl&&' — загружено'}<input type="file" accept="image/*" onChange={e=>void upload(e.target.files?.[0],setMediaFileUrl)} className="mt-1 w-full text-xs"/></label><label className="block text-sm">Современное фото (необязательно){mediaCurrentUrl&&' — загружено'}<input type="file" accept="image/*" onChange={e=>void upload(e.target.files?.[0],setMediaCurrentUrl)} className="mt-1 w-full text-xs"/></label><select required value={mediaSourceId} onChange={e=>setMediaSourceId(e.target.value)} className="w-full rounded-lg border p-2"><option value="">Источник фотографии</option>{sources.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select>{sources.length===0&&<p className="text-xs text-amber-700">Сначала добавьте источник в карточке объекта: публикация архивного фото без источника невозможна.</p>}<input required value={mediaRights} onChange={e=>setMediaRights(e.target.value)} placeholder="Права: например, из фондов музея" className="w-full rounded-lg border p-2"/><input required value={mediaAlt} onChange={e=>setMediaAlt(e.target.value)} placeholder="Alt-текст: что изображено" className="w-full rounded-lg border p-2"/><input type="date" value={mediaDate} onChange={e=>setMediaDate(e.target.value)} className="w-full rounded-lg border p-2"/><label className="flex gap-2 text-sm"><input type="checkbox" checked={mediaApproximate} onChange={e=>setMediaApproximate(e.target.checked)}/>Приблизительная дата съёмки</label><button disabled={!mediaFileUrl} className="rounded-lg bg-slate-900 px-4 py-2 text-white disabled:opacity-50">Создать черновик</button></form>
    </div>
    <div className="grid gap-5 lg:grid-cols-2 xl:grid-cols-3">
      <List title="Люди" entity="person" busy={busy} onTransition={transition} rows={people.map(p=>({id:p.id,title:p.name,subtitle:`/${p.slug}`,status:p.editorialStatus}))}/>
      <List title="Хронология" entity="timeline_entry" busy={busy} onTransition={transition} rows={timeline.map(t=>({id:t.id,title:t.title,subtitle:`${t.objectTitle} · ${t.dateFrom??'без даты'}`,status:t.editorialStatus}))}/>
      <List title="События" entity="historical_event" busy={busy} onTransition={transition} rows={events.map(ev=>({id:ev.id,title:ev.title,subtitle:`/${ev.slug} · ${ev.dateFrom??'без даты'}`,status:ev.editorialStatus}))}/>
      <List title="Архивные фото" entity="archive_media" busy={busy} onTransition={transition} rows={media.map(m=>({id:m.id,title:m.altText,subtitle:`${m.objectTitle}${m.hasCurrentPair?' · пара «тогда/сейчас»':''}`,status:m.editorialStatus}))}/>
      <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">Связи людей и мест</h2>{relations.length?<ul className="mt-3 max-h-96 space-y-2 overflow-auto text-sm">{relations.map((r,i)=><li key={`${r.objectId}-${r.personId}-${i}`} className="border-b pb-2"><p className="font-medium">{r.personName}</p><p className="text-xs text-slate-500">{r.objectTitle} · {r.relationType}</p></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">Пока пусто</p>}</section>
    </div>
  </div>
}
type Row={id:string;title:string;subtitle:string;status:string}
function List({title,entity,rows,busy,onTransition}:{title:string;entity:WorkflowEntity;rows:Row[];busy:boolean;onTransition:(entity:WorkflowEntity,id:string,status:string)=>Promise<void>}){
  return <section className="rounded-xl border bg-white p-4"><h2 className="font-semibold">{title}</h2>{rows.length?<ul className="mt-3 max-h-96 space-y-3 overflow-auto text-sm">{rows.map(r=><li key={r.id} className="border-b pb-2"><p className="font-medium">{r.title}</p><p className="text-xs text-slate-500">{r.subtitle} · {STATUS_RU[r.status]??r.status}</p><div className="mt-1 flex flex-wrap gap-1">{allowedTransitions(r.status).map(s=><button key={s} type="button" disabled={busy} onClick={()=>void onTransition(entity,r.id,s)} className="rounded border px-2 py-0.5 text-xs text-slate-700 hover:bg-slate-50 disabled:opacity-50">{ACTION_RU[s]??s}</button>)}</div></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">Пока пусто</p>}</section>
}
