events {}
http {
  server {
    listen 8443 ssl;
    server_name xn--80ayho4cq.site;
    ssl_certificate /etc/letsencrypt/live/xn--80ayho4cq.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xn--80ayho4cq.site/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    auth_basic "Pamyat preview";
    auth_basic_user_file /etc/nginx/.htpasswd;
    client_max_body_size 101m;
    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    add_header X-Content-Type-Options nosniff always;
    location / {
      proxy_pass http://craft-map-preview-app:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $host:8443;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
