import type { Metadata } from 'next'
import Link from 'next/link';import {notFound}from'next/navigation';import{pg}from'@/lib/db';import{isFeatureEnabled}from'@/lib/feature-flags';import RouteWalk from '@/components/RouteWalk';import OfflineRoutePackage from '@/components/OfflineRoutePackage';import type{PublicRouteStop}from'@/lib/routes'
export const dynamic='force-dynamic';type Params={params:Promise<{slug:string}>}
type RouteRow={id:string;title:string;summary:string|null;description:string|null;minutes:number|null;distance:number|null;version:number;difficulty:string|null;accessibilityProfile:Record<string,string|number|boolean|null>}
const loadRoute=async(slug:string)=>{const[r]=await pg<RouteRow[]>`select id,title,summary,description,estimated_duration_minutes as minutes,distance_meters as distance,offline_package_version as version,difficulty,accessibility_profile as "accessibilityProfile" from routes where slug=${slug} and status='published'`;return r}
export async function generateMetadata({params}:Params):Promise<Metadata>{
 if(!isFeatureEnabled('routes_enabled'))return{}
 const{slug}=await params;const r=await loadRoute(slug);if(!r)return{}
 const title=`${r.title} — маршрут по памятным местам Тюмени`
 const description=r.summary??'Готовый пешеходный маршрут по памятным местам Тюмени с аудиогидом.'
 return{title,description,alternates:{canonical:`/routes/${slug}`},openGraph:{type:'article',locale:'ru_RU',siteName:'Память Тюмени',title,description,url:`/routes/${slug}`}}
}
export default async function RoutePage({params}:Params){if(!isFeatureEnabled('routes_enabled'))notFound();const{slug}=await params;const r=await loadRoute(slug);if(!r)notFound();const stops=await pg<PublicRouteStop[]>`select rs.id,rs.object_id as "objectId",o.title,o.address,st_x(o.geom) as lng,st_y(o.geom) as lat,rs.position,rs.arrival_radius_meters as "arrivalRadiusMeters",rs.recommended_duration_minutes as "recommendedDurationMinutes",rs.intro_text as "introText",rs.directions_text as "directionsText",coalesce(sa.audio_url,fa.audio_url,o.audio_url) as "audioUrl",coalesce(sa.script_text,fa.script_text,o.audio_text) as "audioText",sa.audio_url as "shortAudioUrl",sa.script_text as "shortAudioText",fa.audio_url as "fullAudioUrl",fa.script_text as "fullAudioText" from route_stops rs join objects o on o.id=rs.object_id left join audio_variants sa on sa.id=rs.short_audio_variant_id left join audio_variants fa on fa.id=rs.full_audio_variant_id where rs.route_id=${r.id} and o.published order by rs.position`;const access=Object.entries(r.accessibilityProfile??{}).filter(([,v])=>v!==null&&v!==false&&v!=='');return <main className="mx-auto max-w-3xl px-4 py-8"><Link href="/routes" className="text-[var(--accent)]">← Все маршруты</Link><h1 className="mt-5 text-3xl font-semibold">{r.title}</h1>{r.summary&&<p className="mt-2 text-lg text-[var(--ink-muted)]">{r.summary}</p>}<p className="mt-4 text-sm">{stops.length} точек{r.minutes?` · ${r.minutes} мин`:''}{r.distance?` · ${(r.distance/1000).toFixed(1)} км`:''}{r.difficulty?` · ${r.difficulty}`:''}</p>{access.length>0&&<section className="mt-4 rounded-xl border border-[var(--hairline)] p-3"><h2 className="text-sm font-semibold">Доступность</h2><ul className="mt-1 space-y-1 text-sm text-[var(--ink-muted)]">{access.map(([k,v])=><li key={k}>{v===true?k:`${k}: ${v}`}</li>)}</ul></section>}{r.description&&<p className="mt-5 whitespace-pre-line">{r.description}</p>}{isFeatureEnabled('offline_packages_enabled')&&<OfflineRoutePackage slug={slug} version={r.version}/>}<RouteWalk routeId={r.id} version={r.version} stops={stops}/></main>}
