import { NextRequest,NextResponse } from 'next/server'
import { pg } from '@/lib/db'
import { requireRole } from '@/lib/guard'
import { routeInputSchema } from '@/lib/routes'
import { uuidSchema } from '@/lib/validation'
type Params={params:Promise<{id:string}>}
export async function GET(_r:Request,{params}:Params){const guard=await requireRole('editor');if(guard.error)return guard.error;const{id}=await params;if(!uuidSchema.safeParse(id).success)return NextResponse.json({error:'Не найден'},{status:404});const [route]=await pg`select * from routes where id=${id}`;if(!route)return NextResponse.json({error:'Не найден'},{status:404});const stops=await pg`select * from route_stops where route_id=${id} order by position`;return NextResponse.json({...route,stops})}
// Статус меняется только через workflow-эндпоинт; PUT правит контент и остановки.
export async function PUT(req:NextRequest,{params}:Params){const guard=await requireRole('editor');if(guard.error)return guard.error;const{id}=await params;if(!uuidSchema.safeParse(id).success)return NextResponse.json({error:'Не найден'},{status:404});const parsed=routeInputSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Некорректные данные',details:parsed.error.flatten()},{status:400});const d=parsed.data;try{const ok=await pg.begin(async sql=>{const [row]=await sql<{id:string}[]>`update routes set slug=${d.slug},title=${d.title},summary=${d.summary??null},description=${d.description??null},cover_url=${d.coverUrl??null},theme=${d.theme??null},mode=${d.mode},estimated_duration_minutes=${d.estimatedDurationMinutes??null},distance_meters=${d.distanceMeters??null},difficulty=${d.difficulty??null},age_group=${d.ageGroup??null},accessibility_profile=${JSON.stringify(d.accessibilityProfile)}::jsonb,offline_package_version=offline_package_version+1,updated_at=now() where id=${id} returning id`;if(!row)return false;await sql`delete from route_stops where route_id=${id}`;for(const[i,s]of d.stops.entries())await sql`insert into route_stops(route_id,object_id,position,arrival_radius_meters,recommended_duration_minutes,intro_text,directions_text,gps_autoplay) values(${id},${s.objectId},${i+1},${s.arrivalRadiusMeters},${s.recommendedDurationMinutes??null},${s.introText??null},${s.directionsText??null},${s.gpsAutoplay})`;const{appendAdminAudit}=await import('@/lib/audit');await appendAdminAudit(sql,guard.session,{action:'update',entity:'route',entityId:id,metadata:{status:'content'}});return true})
if(ok){try{const{refreshRouteLegs}=await import('@/lib/route-legs-server');await refreshRouteLegs(id)}catch(error){console.error(error)}}
return ok?NextResponse.json({ok:true}):NextResponse.json({error:'Не найден'},{status:404})}catch(error){console.error(error);return NextResponse.json({error:'Не удалось сохранить маршрут. Проверьте уникальность slug и список остановок.'},{status:409})}}
export async function DELETE(_r:Request,{params}:Params){const guard=await requireRole('admin');if(guard.error)return guard.error;const{id}=await params;if(!uuidSchema.safeParse(id).success)return NextResponse.json({error:'Не найден'},{status:404});const rows=await pg`delete from routes where id=${id} and status<>'published' returning id`;return rows.length?NextResponse.json({ok:true}):NextResponse.json({error:'Опубликованный маршрут сначала архивируйте'},{status:409})}
